## 1. Create a NumPy array named arr containing integers from 0 to 5. Print its data type.

In [2]:
import numpy as np 

arr=np.array([0,1,2,3,4,5])

print(arr.dtype)

int64


## 2.Given a NumPy array 'arr', check if its data type is float64.

### arr = np.array([1.5, 2.6, 3.7])

In [3]:
import numpy as np 
arr = np.array([1.5, 2.6, 3.7])

print(arr.dtype=='float64')

True


## 3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [4]:
import numpy as np

arr=np.array([1+3j,2+4j,5+6j])

print(arr.dtype)

complex128


## 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [9]:
import numpy as np 

arr=np.array([0,1,2,3,4,5])

print(arr)

arr_float32=arr.astype(np.float32)

print(arr_float32.dtype)
print(arr_float32)


[0 1 2 3 4 5]
float32
[0. 1. 2. 3. 4. 5.]


## 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [15]:
import numpy as np


arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

print("Original array data type:", arr.dtype)
print("Converted array data type:", arr_float32.dtype)
print("Converted array:", arr_float32)


Original array data type: float64
Converted array data type: float32
Converted array: [1.1 2.2 3.3]


## 6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [16]:
import numpy as np

def array_attributes(arr):
    
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype


arr = np.array([[1, 2, 3], [4, 5, 6]])
attributes = array_attributes(arr)
print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])


Shape: (2, 3)
Size: 6
Data type: int64


## 7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [17]:
import numpy as np

def array_dimension(arr):
    
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print("Dimensionality:", dimension)


Dimensionality: 2


## 8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [18]:
import numpy as np

def item_size_info(arr):
    
    item_size = arr.itemsize  # Size of each element in bytes
    total_size = arr.nbytes   # Total size of the array in bytes
    return item_size, total_size

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
size_info = item_size_info(arr)
print("Item size (in bytes):", size_info[0])
print("Total size (in bytes):", size_info[1])


Item size (in bytes): 4
Total size (in bytes): 24


## 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [19]:
import numpy as np

def array_strides(arr):
   
    return arr.strides


arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)


Strides: (24, 8)


## 10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [20]:
import numpy as np

def shape_stride_relationship(arr):
   
    shape = arr.shape
    strides = arr.strides
    return shape, strides


arr = np.array([[1, 2, 3], [4, 5, 6]])
shape_strides = shape_stride_relationship(arr)
print("Shape:", shape_strides[0])
print("Strides:", shape_strides[1])


Shape: (2, 3)
Strides: (24, 8)


## 11.Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.

In [21]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

# Example usage
arr = create_zeros_array(5)
print(arr)


[0. 0. 0. 0. 0.]


## 12.Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.

In [22]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

matrix = create_ones_matrix(3, 4)
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 13.Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.

In [23]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)


range_array = generate_range_array(1, 10, 2)
print(range_array)


[1 3 5 7 9]


## 14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).

In [24]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)


linear_space_array = generate_linear_space(0.0, 1.0, 5)
print(linear_space_array)


[0.   0.25 0.5  0.75 1.  ]


## 15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.

In [25]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

identity_matrix = create_identity_matrix(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 16. Write a function that takes a Python list and converts it into a NumPy array.

In [26]:
import numpy as np

def list_to_array(py_list):
    return np.array(py_list)

py_list = [1, 2, 3, 4, 5]
array = list_to_array(py_list)
print(array)


[1 2 3 4 5]


## 17.Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data

In [27]:
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new array view of the original array
array_view = original_array.view()

# Print the original array and its view
print("Original array:")
print(original_array)

print("\nArray view:")
print(array_view)




Original array:
[[1 2 3]
 [4 5 6]]

Array view:
[[1 2 3]
 [4 5 6]]


In [28]:
# Modify the original array
original_array[0, 0] = 99

print("\nModified original array:")
print(original_array)

print("\nModified array view:")
print(array_view)



Modified original array:
[[99  2  3]
 [ 4  5  6]]

Modified array view:
[[99  2  3]
 [ 4  5  6]]


## 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [29]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_array = concatenate_arrays(arr1, arr2, axis=0)
print(concatenated_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [30]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_array = np.concatenate((arr1, arr2), axis=1)
print(concatenated_array)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [31]:
import numpy as np

def vertical_stack(arrays):
    return np.vstack(arrays)

# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
stacked_array = vertical_stack([arr1, arr2, arr3])
print(stacked_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [32]:
import numpy as np

def range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

# Example usage
range_arr = range_array(1, 10, 2)
print(range_arr)


[1 3 5 7 9]


## 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [33]:
import numpy as np

def generate_linear_space():
    return np.linspace(0, 1, 10)

# Example usage
linear_space_array = generate_linear_space()
print(linear_space_array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [34]:
import numpy as np

def log_space_array():
    return np.logspace(0, 3, 5)

# Example usage
log_space_arr = log_space_array()
print(log_space_arr)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


## 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [35]:
import pandas as pd
import numpy as np

# Create a NumPy array with random integers
array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame
df = pd.DataFrame(array, columns=['Column1', 'Column2', 'Column3'])
print(df)


   Column1  Column2  Column3
0       91       56       40
1       78       47       97
2       48       70       93
3       47       12       95
4       31       65       66


## 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [36]:
import pandas as pd
import numpy as np

def replace_negatives(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {'A': [1, -2, 3, -4, 5], 'B': [-10, 20, -30, 40, 50]}
df = pd.DataFrame(data)
df = replace_negatives(df, 'A')
print(df)


   A   B
0  1 -10
1  0  20
2  3 -30
3  0  40
4  5  50


## 26.Access the 3rd element from the given NumPy array.
####  arr = np.array([10, 20, 30, 40, 50])

In [37]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2 since indexing starts from 0)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


## 27.Retrieve the element at index (1, 2) from the 2D NumPy array.
   arr_2d = np.array([[1, 2, 3],

                  [4, 5, 6],

                  [7, 8, 9]])

In [38]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Access the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


## 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

#### arr = np.array([3, 8, 2, 10, 5, 7])

In [39]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Extract elements greater than 5 using boolean indexing
elements_greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", elements_greater_than_5)


Elements greater than 5: [ 8 10  7]


## 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

#### arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]  # Slicing stops at index 6, which is exclusive

print("Elements from index 2 to 5:", sliced_elements)


Elements from index 2 to 5: [3 4 5 6]


## 30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
      arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])


In [41]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:")
print(sub_array)


Extracted sub-array:
[[2 3]
 [5 6]]


## 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array. 

In [42]:
import numpy as np

def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
extracted_elements = extract_elements(arr, row_indices, col_indices)
print(extracted_elements)  # Output: [2, 6, 7]


[2 6 7]


## 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [43]:
import numpy as np

def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

# Example usage
arr = np.array([1, 5, 8, 3, 7])
filtered_arr = filter_greater_than(arr, 4)
print(filtered_arr)  # Output: [5, 8, 7]


[5 8 7]


## 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in threeseparate arrays for each dimension.

In [44]:
import numpy as np

def extract_3d_elements(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]

# Example usage
arr = np.arange(27).reshape(3, 3, 3)
idx1 = np.array([0, 1, 2])
idx2 = np.array([1, 0, 2])
idx3 = np.array([2, 1, 0])
extracted_elements = extract_3d_elements(arr, idx1, idx2, idx3)
print(extracted_elements)  # Output: [ 5,  9, 18]


[ 5 10 24]


## 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [45]:
import numpy as np

def elements_with_conditions(arr):
    return arr[(arr > 3) & (arr < 8)]

# Example usage
arr = np.array([1, 3, 5, 7, 9])
filtered_arr = elements_with_conditions(arr)
print(filtered_arr)  # Output: [5, 7]


[5 7]


## 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [46]:
import numpy as np

def extract_with_row_col_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1])
col_indices = np.array([2, 1])
extracted_elements = extract_with_row_col_indices(arr, row_indices, col_indices)
print(extracted_elements)  # Output: [3, 5]


[3 5]


## 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [47]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr + 5
print(result)
# Output:
# [[ 6  7  8]
#  [ 9 10 11]
#  [12 13 14]]


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [48]:
import numpy as np

arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # Shape (3, 4)
result = arr1.T * arr2
print(result)
# Output:
# [[ 2  4  6  8]
#  [15 18 21 24]
#  [36 40 44 48]]


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


## 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [49]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])  # Shape (4, 3)
result = arr1 + arr2.T
print(result)
# Output:
# [[ 6 10 14]
#  [ 7 11 15]
#  [ 8 12 16]
#  [ 9 13 17]]


[[ 6 10 14 18]
 [ 7 11 15 19]
 [ 8 12 16 20]]


## 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [50]:
import numpy as np

arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])      # Shape (1, 3)
result = arr1 + arr2
print(result)
# Output:
# [[5 6 7]
#  [6 7 8]
#  [7 8 9]]


[[5 6 7]
 [6 7 8]
 [7 8 9]]


## 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility

In [51]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[1, 2], [3, 4]])        # Shape (2, 2)

# To multiply these arrays, we need to adjust the shape
# Broadcast arr1 by adding extra dimensions to match arr2 if logical
try:
    result = arr1[:, :arr2.shape[1]] * arr2  # Broadcasting after slicing
    print(result)
except ValueError as e:
    print("Error:", e)
# Output: Cannot broadcast due to shape incompatibility


[[ 1  4]
 [12 20]]


## 41. Calculate column wise mean for the given array:
   ## arr = np.array([[1, 2, 3], [4, 5, 6]]) 

In [52]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Calculate the column-wise mean
column_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_mean)


Column-wise mean: [2.5 3.5 4.5]


## 42.  Find maximum value in each row of the given array:
 ## arr = np.array([[1, 2, 3], [4, 5, 6]])

In [53]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find the maximum value in each row
row_max = np.max(arr, axis=1)

print("Maximum values in each row:", row_max)


Maximum values in each row: [3 6]


## 43. For the given array, find indices of maximum value in each column.
##arr = np.array([[1, 2, 3], [4, 5, 6]])

In [54]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find the indices of the maximum value in each column
column_max_indices = np.argmax(arr, axis=0)

print("Indices of maximum values in each column:", column_max_indices)


Indices of maximum values in each column: [1 1 1]


## 44. For the given array, apply custom function to calculate moving sum along rows

## arr = np.array([[1, 2, 3], [4, 5, 6]])

In [1]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define the custom function to calculate moving sum
def moving_sum(arr, window_size):
    # Initialize an empty array to store the moving sums
    result = np.zeros_like(arr)

    # Loop through each row
    for i in range(arr.shape[0]):
        # Loop through each element in the row, applying the moving sum
        for j in range(arr.shape[1] - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])
    
    return result

# Apply the custom function with window size 2
moving_sum_result = moving_sum(arr, window_size=2)
print(moving_sum_result)


[[ 3  5  0]
 [ 9 11  0]]


## 45. In the given array, check if all elements in each column are even.

##  arr = np.array([[2, 4, 6], [3, 5, 7]])

In [2]:
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])
result = np.all(arr % 2 == 0, axis=0)
print(result)


[False False False]


## 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
## original_array = np.array([1, 2, 3, 4, 5, 6])

In [3]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3
reshaped_array = original_array.reshape(m, n)
print(reshaped_array)


[[1 2 3]
 [4 5 6]]


## 47. Create a function that takes a matrix as input and returns the flattened array.

## input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


## 48. Write a function that concatenates two given arrays along a specified axis
## array1 = np.array([[1, 2], [3, 4]])
##  array2 = np.array([[5, 6], [7, 8]])

In [5]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print(concatenated_array)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
import numpy as np

def split_array(arr, sections, axis):
    return np.array_split(arr, sections, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arrays = split_array(original_array, 3, axis=0)
print(split_arrays)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


## 50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]

In [7]:
import numpy as np

def insert_and_delete(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


[ 1 10  4 11  5]


## 51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.

In [8]:
import numpy as np

arr1 = np.random.randint(1, 10, 10)  # Array with random integers
arr2 = np.arange(1, 11)  # Array with integers from 1 to 10

result_add = arr1 + arr2
print(result_add)


[ 4  9  6  6 12  7 14 17 11 11]


## 52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.

In [9]:
import numpy as np

arr1 = np.arange(10, 0, -1)  # Sequential integers from 10 to 1
arr2 = np.arange(1, 11)  # Integers from 1 to 10

result_subtract = arr1 - arr2
print(result_subtract)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


## 53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.


In [10]:
import numpy as np

arr1 = np.random.randint(1, 10, 5)  # Array with random integers
arr2 = np.arange(1, 6)  # Integers from 1 to 5

result_multiply = arr1 * arr2
print(result_multiply)


[ 7  4 15 28 45]


## 54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.

In [11]:
import numpy as np

arr1 = np.arange(2, 11, 2)  # Even integers from 2 to 10
arr2 = np.arange(1, 6)  # Integers from 1 to 5

result_division = arr1 / arr2
print(result_division)


[2. 2. 2. 2. 2.]


## 55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

In [12]:
import numpy as np

arr1 = np.arange(1, 6)  # Integers from 1 to 5
arr2 = arr1[::-1]  # Reversed array of arr1 (5, 4, 3, 2, 1)

result_exponentiation = arr1 ** arr2
print(result_exponentiation)


[ 1 16 27 16  5]


## 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

#### arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [13]:
import numpy as np

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(occurrences)


3


## 57. Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
#### arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [15]:
import numpy as np

def extract_uppercase(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase(arr)
print(uppercase_characters)



['H' 'W' 'OAI' 'GPT']


## 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#### arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [16]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
replaced_array = replace_substring(arr, old_substring, new_substring)
print(replaced_array)


['orange' 'banana' 'grape' 'pineorange']


## 59. Write a function that concatenates strings in a NumPy array element-wise.

  arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [17]:
import numpy as np

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_array = concatenate_strings(arr1, arr2)
print(concatenated_array)


['HelloOpen' 'WorldAI']


## 60. Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [18]:
import numpy as np

def longest_string_length(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
length_of_longest_string = longest_string_length(arr)
print(length_of_longest_string)


9


## 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [19]:
import numpy as np

# Create dataset
data = np.random.randint(1, 1001, 100)

# Compute statistics
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_dev}")


Mean: 538.79
Median: 561.0
Variance: 89663.2059
Standard Deviation: 299.43815037499814


## 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [20]:
import numpy as np

# Generate random numbers
data = np.random.randint(1, 101, 50)

# Compute percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")


25th Percentile: 29.75
75th Percentile: 84.5


## 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

In [21]:
import numpy as np

# Create two arrays
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

# Compute correlation coefficient
correlation_matrix = np.corrcoef(arr1, arr2)
correlation_coefficient = correlation_matrix[0, 1]

print(f"Correlation Coefficient: {correlation_coefficient}")


Correlation Coefficient: -0.03406280506789443


## 64. Create two matrices and perform matrix multiplication using NumPy's dot function.

In [22]:
import numpy as np

# Create two matrices
matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Result of Matrix Multiplication:")
print(result)


Matrix 1:
[[1 1 8]
 [7 3 8]
 [6 4 5]]
Matrix 2:
[[1 4 2]
 [1 8 5]
 [4 2 4]]
Result of Matrix Multiplication:
[[34 28 39]
 [42 68 61]
 [30 66 52]]


## 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [23]:
import numpy as np

# Create array of integers
data = np.random.randint(10, 1001, 50)

# Calculate percentiles and quartiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  # Median
percentile_90 = np.percentile(data, 90)
quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"1st Quartile: {quartile_1}")
print(f"3rd Quartile: {quartile_3}")


10th Percentile: 86.0
50th Percentile (Median): 449.5
90th Percentile: 867.7
1st Quartile: 206.0
3rd Quartile: 656.0


## 66. Create a NumPy array of integers and find the index of a specific element.

In [24]:
import numpy as np

# Create an array of integers
arr = np.array([10, 20, 30, 40, 50])

# Find the index of a specific element
element = 30
index = np.where(arr == element)[0][0]

print(f"Index of element {element}: {index}")


Index of element 30: 2


## 67. Generate a random NumPy array and sort it in ascending order

In [26]:
import numpy as np

# Generate a random array
arr = np.random.rand(10)

# Sort the array in ascending order
sorted_arr = np.sort(arr)

print("Original Array:")
print(arr)
print("Sorted Array:")
print(sorted_arr)


Original Array:
[0.94081404 0.0079542  0.6445719  0.60069006 0.06411255 0.18155432
 0.17137565 0.85431468 0.9703843  0.86675422]
Sorted Array:
[0.0079542  0.06411255 0.17137565 0.18155432 0.60069006 0.6445719
 0.85431468 0.86675422 0.94081404 0.9703843 ]


## 68. Filter elements >20  in the given NumPy array.

#### arr = np.array([12, 25, 6, 42, 8, 30])

In [27]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

print(filtered_arr)


[25 42 30]


## 69. Filter elements which are divisible by 3 from a given NumPy array.

#### arr = np.array([1, 5, 8, 12, 15])

In [28]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

print(filtered_arr)


[12 15]


## 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

#### arr = np.array([10, 20, 30, 40, 50])

In [29]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 inclusive
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print(filtered_arr)


[20 30 40]


## 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
####  arr = np.array([1, 2, 3])

In [30]:
import numpy as np

arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

print(f"Byte order: {byte_order}")


Byte order: =


## 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
#### arr = np.array([1, 2, 3], dtype=np.int32)

In [31]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(inplace=True)

print(arr)


[16777216 33554432 50331648]


## 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

####  arr = np.array([1, 2, 3], dtype=np.int32)

In [33]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Create a view with swapped byte order
swapped_arr = np.asarray(arr, dtype=arr.dtype.newbyteorder())

print("Original array:")
print(arr)
print("Array with swapped byte order:")
print(swapped_arr)



Original array:
[1 2 3]
Array with swapped byte order:
[1 2 3]


## 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

#### arr = np.array([1, 2, 3], dtype=np.int32)

In [34]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

# Determine system endianness
system_endianness = '=' if sys.byteorder == 'little' else '>'

# Swap byte order conditionally based on system endianness
if arr.dtype.byteorder != system_endianness:
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr

print("Original array:")
print(arr)
print("Array with swapped byte order (if needed):")
print(swapped_arr)


Original array:
[1 2 3]
Array with swapped byte order (if needed):
[1 2 3]


## 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

#### arr = np.array([1, 2, 3], dtype=np.int32)

In [35]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

# Determine system's native byte order
system_byteorder = '=' if sys.byteorder == 'little' else '>'

# Check if byte swapping is necessary
if arr.dtype.byteorder not in ('=', system_byteorder):
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")


Byte swapping is not necessary.


## 76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.

In [36]:
import numpy as np

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

print("Original array (arr1):")
print(arr1)
print("Modified copy (copy_arr):")
print(copy_arr)


Original array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr):
[100   2   3   4   5   6   7   8   9  10]


## 77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.

In [37]:
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[1:, 1:]

# Modify an element in view_slice
view_slice[0, 0] = 99

print("Original matrix:")
print(matrix)
print("Modified view_slice:")
print(view_slice)


Original matrix:
[[ 8  7  1]
 [ 6 99  9]
 [ 7  6  8]]
Modified view_slice:
[[99  9]
 [ 6  8]]


## 78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

In [38]:
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:, 1:]

# Broadcast addition of 5 to view_b
view_b += 5

print("Original array_a:")
print(array_a)
print("Modified view_b:")
print(view_b)


Original array_a:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]
Modified view_b:
[[10 11]
 [13 14]
 [16 17]]


## 79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array.

In [39]:
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 99

print("Original orig_array:")
print(orig_array)
print("Modified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[99  2  3  4]
 [ 5  6  7  8]]
Modified reshaped_view:
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


## 80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

In [40]:
import numpy as np

data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 99

print("Original data:")
print(data)
print("Modified data_copy:")
print(data_copy)


Original data:
[[8 3 7 3]
 [6 2 8 8]
 [9 9 8 4]]
Modified data_copy:
[99  7  6  8  8  9  9  8]


## 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [41]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition and subtraction
addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Addition result:")
print(addition_result)
print("Subtraction result:")
print(subtraction_result)


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Addition result:
[[ 6  8]
 [10 12]]
Subtraction result:
[[-4 -4]
 [-4 -4]]


## 82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.


In [42]:
import numpy as np

C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))

# Matrix multiplication
multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)
print("Matrix D:")
print(D)
print("Matrix multiplication result:")
print(multiplication_result)


Matrix C:
[[6 6]
 [4 3]
 [7 5]]
Matrix D:
[[1 7 9 1]
 [7 3 2 8]]
Matrix multiplication result:
[[48 60 66 54]
 [25 37 42 28]
 [42 64 73 47]]


## 83. Create a matrix E and find its transpose.

In [43]:
import numpy as np

C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))

# Matrix multiplication
multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)
print("Matrix D:")
print(D)
print("Matrix multiplication result:")
print(multiplication_result)


Matrix C:
[[7 6]
 [3 9]
 [6 1]]
Matrix D:
[[1 8 9 4]
 [1 1 8 6]]
Matrix multiplication result:
[[ 13  62 111  64]
 [ 12  33  99  66]
 [  7  49  62  30]]


## 84. Generate a square matrix F and compute its determinant.

## 85. Create a square matrix G and find its inverse.